### ISSUE TITLE
'HttpClient' does not contain a definition for 'PostJsonAsync' and no accessible extension method 'PostJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by bigabdoul** [enkodellc/blazorboilerplate#353] opened 2020-06-11 14:12 UTC
PostJsonAsync does not exist on HttpClient but Post**As**JsonAsync does. I'm using .NET Core 3.1.300  and Visual Studio 2019 Version 16.6.1.

Build output (real path shortened):

1>------ Build started: Project: BlazorBoilerplate.Shared, Configuration: Debug_CSB Any CPU ------
2>------ Skipped Build: Project: docker-compose, Configuration: Debug_CSB Any CPU ------
2>Project not selected to build for this solution configuration 
1>BlazorBoilerplate.Shared -> C:\blazorboilerplate\src\BlazorBoilerplate.Shared\bin\Debug_CSB\netstandard2.1\BlazorBoilerplate.Shared.dll
3>------ Build started: Project: BlazorBoilerplate.CommonUI, Configuration: Debug_CSB Any CPU ------
4>------ Build started: Project: BlazorBoilerplate.Storage, Configuration: Debug Any CPU ------
4>C:\blazorboilerplate\src\BlazorBoilerplate.Storage\Stores\TenantStore.cs(41,35,41,41): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
4>C:\blazorboilerplate\src\BlazorBoilerplate.Storage\Stores\TenantStore.cs(50,35,50,41): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
4>C:\blazorboilerplate\src\BlazorBoilerplate.Storage\Stores\TenantStore.cs(64,27,64,37): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
4>BlazorBoilerplate.Storage -> C:\blazorboilerplate\src\BlazorBoilerplate.Storage\bin\Debug\netcoreapp3.1\BlazorBoilerplate.Storage.dll
4>Done building project "BlazorBoilerplate.Storage.csproj".
5>------ Build started: Project: BlazorBoilerplate.Storage.Tests, Configuration: Debug Any CPU ------
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\AppState.cs(10,14,10,51): warning CS0105: The using directive for 'StatusCodes' appeared previously in this namespace
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Services\Implementations\UserProfileApi.cs(21,38,21,66): error CS1061: 'HttpClient' does not contain a definition for 'GetJsonAsync' and no accessible extension method 'GetJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Services\Implementations\UserProfileApi.cs(26,38,26,67): error CS1061: 'HttpClient' does not contain a definition for 'PostJsonAsync' and no accessible extension method 'PostJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Services\Implementations\AuthorizeApi.cs(79,42,79,71): error CS1061: 'HttpClient' does not contain a definition for 'PostJsonAsync' and no accessible extension method 'PostJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Services\Implementations\AuthorizeApi.cs(99,38,99,67): error CS1061: 'HttpClient' does not contain a definition for 'PostJsonAsync' and no accessible extension method 'PostJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Services\Implementations\AuthorizeApi.cs(104,38,104,67): error CS1061: 'HttpClient' does not contain a definition for 'PostJsonAsync' and no accessible extension method 'PostJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Services\Implementations\AuthorizeApi.cs(109,38,109,67): error CS1061: 'HttpClient' does not contain a definition for 'PostJsonAsync' and no accessible extension method 'PostJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Services\Implementations\AuthorizeApi.cs(114,38,114,67): error CS1061: 'HttpClient' does not contain a definition for 'PostJsonAsync' and no accessible extension method 'PostJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Services\Implementations\AuthorizeApi.cs(119,38,119,67): error CS1061: 'HttpClient' does not contain a definition for 'PostJsonAsync' and no accessible extension method 'PostJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Services\Implementations\AuthorizeApi.cs(125,60,125,88): error CS1061: 'HttpClient' does not contain a definition for 'GetJsonAsync' and no accessible extension method 'GetJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Services\Implementations\AuthorizeApi.cs(137,60,137,88): error CS1061: 'HttpClient' does not contain a definition for 'GetJsonAsync' and no accessible extension method 'GetJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Services\Implementations\AuthorizeApi.cs(144,38,144,67): error CS1061: 'HttpClient' does not contain a definition for 'PostJsonAsync' and no accessible extension method 'PostJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Pages\Account\Profile.razor(110,38,110,67): error CS1061: 'HttpClient' does not contain a definition for 'PostJsonAsync' and no accessible extension method 'PostJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Pages\TodoList.razor(103,53,103,81): error CS1061: 'HttpClient' does not contain a definition for 'PutJsonAsync' and no accessible extension method 'PutJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Pages\TodoList.razor(161,53,161,82): error CS1061: 'HttpClient' does not contain a definition for 'PostJsonAsync' and no accessible extension method 'PostJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Pages\Admin\Users.razor(280,42,280,70): error CS1061: 'HttpClient' does not contain a definition for 'PutJsonAsync' and no accessible extension method 'PutJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Pages\Admin\Users.razor(342,46,342,75): error CS1061: 'HttpClient' does not contain a definition for 'PostJsonAsync' and no accessible extension method 'PostJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Pages\Admin\DbLogViewer.razor(67,16,67,30): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Pages\TestEmail.razor(37,53,37,82): error CS1061: 'HttpClient' does not contain a definition for 'PostJsonAsync' and no accessible extension method 'PostJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Pages\Admin\DbLogViewer.razor(98,13,98,29): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Pages\Admin\Roles.razor(218,42,218,71): error CS1061: 'HttpClient' does not contain a definition for 'PostJsonAsync' and no accessible extension method 'PostJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Pages\Admin\Roles.razor(220,42,220,70): error CS1061: 'HttpClient' does not contain a definition for 'PutJsonAsync' and no accessible extension method 'PutJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
3>C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\Hubs\ChatClient.cs(90,33,90,42): warning CS0649: Field 'ChatClient._username' is never assigned to, and will always have its default value null
3>Done building project "BlazorBoilerplate.CommonUI.csproj" -- FAILED.
6>------ Build started: Project: BlazorBoilerplate.Client, Configuration: Debug_CSB Any CPU ------
6>CSC : error CS0006: Metadata file 'C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\bin\Debug_CSB\netstandard2.1\BlazorBoilerplate.CommonUI.dll' could not be found
6>Done building project "BlazorBoilerplate.Client.csproj" -- FAILED.
7>------ Build started: Project: BlazorBoilerplate.Server, Configuration: Debug_CSB Any CPU ------
5>BlazorBoilerplate.Storage.Tests -> C:\blazorboilerplate\BlazorBoilerplate.Storage.Tests\bin\Debug\netcoreapp3.1\BlazorBoilerplate.Storage.Tests.dll
7>C:\Program Files\dotnet\sdk\3.1.300\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.MvcApplicationPartsDiscovery.targets(54,5): warning RAZORSDK1007: Reference assembly C:\blazorboilerplate\src\BlazorBoilerplate.Client\bin\Debug_CSB\netstandard2.1\BlazorBoilerplate.Client.dll could not be found. This is typically caused by build errors in referenced projects.
7>CSC : error CS0006: Metadata file 'C:\blazorboilerplate\src\BlazorBoilerplate.Client\bin\Debug_CSB\netstandard2.1\BlazorBoilerplate.Client.dll' could not be found
7>CSC : error CS0006: Metadata file 'C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\bin\Debug_CSB\netstandard2.1\BlazorBoilerplate.CommonUI.dll' could not be found
7>Done building project "BlazorBoilerplate.Server.csproj" -- FAILED.
8>------ Build started: Project: BlazorBoilerplate.Server.Tests, Configuration: Debug Any CPU ------
8>CSC : error CS0006: Metadata file 'C:\blazorboilerplate\src\BlazorBoilerplate.Client\bin\Debug_CSB\netstandard2.1\BlazorBoilerplate.Client.dll' could not be found
8>CSC : error CS0006: Metadata file 'C:\blazorboilerplate\src\BlazorBoilerplate.CommonUI\bin\Debug_CSB\netstandard2.1\BlazorBoilerplate.CommonUI.dll' could not be found
8>CSC : error CS0006: Metadata file 'C:\blazorboilerplate\src\BlazorBoilerplate.Server\bin\Debug_CSB\netcoreapp3.1\BlazorBoilerplate.Server.dll' could not be found
8>Done building project "BlazorBoilerplate.Server.Tests.csproj" -- FAILED.
========== Build: 3 succeeded, 4 failed, 0 up-to-date, 1 skipped ==========

**Comment by GioviQ** [comment] 2020-06-11 14:45
duplicate of https://github.com/enkodellc/blazorboilerplate/issues/340

**Closed by GioviQ** 2020-06-11 14:45 UTC
Labels: duplicate

**Comment by enkodellc** [comment] 2020-06-25 19:09
I think the real issue here is that I used a custom class "ApiResponse" to handle response from api calls. There wasn't anything in the previous version of .net Core to do a more complex response. 

Now there is "HttpResponseMessage" which is very similar to our "ApiResponse" So I am going to try and replace our ApiResponseDto with the HttpResponseMessage object to keep in line with the latest .Net Core code. I am going down the Rabit hole of refactoring and removing ApiResponse...
